task1 with diplomas
Vuklorr/java-algos pull request #10
Opened 2023-07-15 10:18 UTC by Vuklorr

2023-07-15 17:34 UTC, DmitriySud requested changes

2023-07-15 17:34 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task1.java
> +    public long diploma(int w, int h, int n) {
w, h, n - лучше всего сразе делать long

2023-07-15 17:34 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task1.java
> +            if((double)(mid / w) * (double)(mid / h) < n) {
В целочисленных задачах лучше не использовать double. Здесь всё должно умещаться, а в худшем случае в java есть длинная арифметика

2023-07-15 17:34 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task1.java
> +            long mid = (left + right) / 2;
Мы же с тобой уже разбирались, что писать `(left + right) / 2`  - опасно из-за переполнения. Лучше `left + (right-left)/2`

2023-07-15 18:04 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task1.java
> +    public long diploma(int w, int h, int n) {
+

2023-07-15 18:04 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task1.java
> +            if((double)(mid / w) * (double)(mid / h) < n) {
+

2023-07-15 18:04 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task1.java
> +            long mid = (left + right) / 2;
+

2023-07-17 14:12 UTC, DmitriySud approved these changes

2023-07-17 14:51 UTC, merged