task2 (bin search)
Vuklorr/java-algos pull request #11
Opened 2023-07-15 13:36 UTC by Vuklorr

2023-07-15 17:40 UTC, DmitriySud requested changes

2023-07-15 17:40 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task2.java
> +        while(left <= right) {
У тебя в предыдущей задаче просто меньше, тут меньше либо равно. Возмьми один стиль и работай либо в c++ стиле с полуинтерваллами, либо с отрезками. Без разницы что, но в одном стиле

2023-07-15 17:40 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task2.java
> +            } else if(nums[left] <= nums[mid]) {
По условию числа различные, на равно не нужно сравнивать

2023-07-15 17:40 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task2.java
> +                if (target > nums[mid] && target <= nums[right]) {
Чёта ничего не понял. Задача просто найти число в отсортированом массиве. Больно много ифов для такой задачи... 

Должно быть что-то типа:
```
if (нашли?) 
  return 
if (меньше?)
  правую границу
else 
  двигаем левую границу
```

2023-07-17 10:08 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task2.java
> +        while(left <= right) {
+

2023-07-17 10:08 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task2.java
> +            } else if(nums[left] <= nums[mid]) {
+

2023-07-17 10:09 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task2.java
> +                if (target > nums[mid] && target <= nums[right]) {
я объединил if - ы, но не знаю, как уменьшить их количество. Они вроде все нужны

2023-07-18 09:35 UTC, DmitriySud commented
Обсудили. Переделать на 2 бин поиска, каждый из которых исследует отдельную функцию

2023-07-18 10:12 UTC, DmitriySud requested changes

2023-07-18 10:12 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task2.java
> +            if(nums[mid] == target) {
target тут лишний. У этого бинпоиска задача не найти таргет, а найти переломный момент. if c таргетом это ad-hoc, а когда его можно избежать, лучше его избежать)

2023-07-18 10:12 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task2.java
> +        return left;
Что вернёт этот бинпоиск, если был разворот относительно нулевого элемента (то есть не было разворота вовсе)?

2023-07-18 10:19 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task2.java
> +            if(nums[mid] == target) {
просто если мы во время поиска разлома случайно найдем таргет, разве это не будет быстрее работать (в некоторых случаях) или особо не влияет на реальное время?

2023-07-18 10:27 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task2.java
> +            if(nums[mid] == target) {
Длина массива до 5000 элементов. То есть у нас будет не более 11 итераций бин поиска. То есть проверим мы 11/5000 массива. То есть вероятность срабатывания 0.22%

Я считаю, что 0.22% производительности можно потерять ради читаемости кода =)
Потому что читаемость кода, также уменьшает вероятность ошибки в разы

2023-07-18 13:58 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task2.java
> +        return left;
Точно не 0 элемент. Либо последний, либо предпоследний. Т.е. у нас должно быть условие при вызове этого метода, что массив именно перевернут?

2023-07-18 21:40 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task2.java
> +        return left;
Ну я бы сделал чтобы когда бин поиск по первой функции не нашёл ни одного подходящего числа, он возвращал -1

2023-07-19 10:43 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task2.java
> +        return left;
\+

2023-07-19 14:14 UTC, DmitriySud approved these changes
Хорошая задача. Много чего из неё вынесли

2023-07-19 14:42 UTC, merged