task3 (bin search)
Vuklorr/java-algos pull request #12
Opened 2023-07-15 14:50 UTC by Vuklorr

2023-07-15 17:46 UTC, DmitriySud requested changes

2023-07-15 17:46 UTC, DmitriySud commented on java/src/main/java/com/algos/binsearch/Task3.java
> +        while(i >= 0 && nums[i] == target) {
Нельзя так 
Если я введу весь массив из одинаковых чисел и попрошу тебя это же число найти, то асимптотика скатится в линейную 

Посмотри `std::lower_bound` и `std::upper_bound` в задаче надо найти именно их

2023-07-17 13:04 UTC, Vuklorr commented on java/src/main/java/com/algos/binsearch/Task3.java
> +        while(i >= 0 && nums[i] == target) {
+

2023-07-17 15:27 UTC, DmitriySud approved these changes
Отлично!

2023-07-17 15:51 UTC, merged